/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as DotaRouteImport } from './routes/dota'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatCharacterIdRouteImport } from './routes/chat.$characterId'

const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const DotaRoute = DotaRouteImport.update({
  id: '/dota',
  path: '/dota',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCharacterIdRoute = ChatCharacterIdRouteImport.update({
  id: '/chat/$characterId',
  path: '/chat/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dota': typeof DotaRoute
  '/guestbook': typeof GuestbookRoute
  '/chat/$characterId': typeof ChatCharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dota': typeof DotaRoute
  '/guestbook': typeof GuestbookRoute
  '/chat/$characterId': typeof ChatCharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dota': typeof DotaRoute
  '/guestbook': typeof GuestbookRoute
  '/chat/$characterId': typeof ChatCharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dota' | '/guestbook' | '/chat/$characterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dota' | '/guestbook' | '/chat/$characterId'
  id: '__root__' | '/' | '/dota' | '/guestbook' | '/chat/$characterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DotaRoute: typeof DotaRoute
  GuestbookRoute: typeof GuestbookRoute
  ChatCharacterIdRoute: typeof ChatCharacterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dota': {
      id: '/dota'
      path: '/dota'
      fullPath: '/dota'
      preLoaderRoute: typeof DotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$characterId': {
      id: '/chat/$characterId'
      path: '/chat/$characterId'
      fullPath: '/chat/$characterId'
      preLoaderRoute: typeof ChatCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DotaRoute: DotaRoute,
  GuestbookRoute: GuestbookRoute,
  ChatCharacterIdRoute: ChatCharacterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
